/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.uk.dalelane;
@org.apache.avro.specific.AvroGenerated
public enum Compass implements org.apache.avro.generic.GenericEnumSymbol<Compass> {
  NORTH, SOUTH, EAST, WEST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Compass\",\"namespace\":\"co.uk.dalelane\",\"symbols\":[\"NORTH\",\"SOUTH\",\"EAST\",\"WEST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
