/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package co.uk.dalelane;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Type3 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8975121787326351619L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Type3\",\"namespace\":\"co.uk.dalelane\",\"fields\":[{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"Compass\",\"symbols\":[\"NORTH\",\"SOUTH\",\"EAST\",\"WEST\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Type3> ENCODER =
      new BinaryMessageEncoder<Type3>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Type3> DECODER =
      new BinaryMessageDecoder<Type3>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Type3> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Type3> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Type3> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Type3>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Type3 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Type3 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Type3 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Type3 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private co.uk.dalelane.Compass direction;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Type3() {}

  /**
   * All-args constructor.
   * @param direction The new value for direction
   */
  public Type3(co.uk.dalelane.Compass direction) {
    this.direction = direction;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return direction;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: direction = (co.uk.dalelane.Compass)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'direction' field.
   * @return The value of the 'direction' field.
   */
  public co.uk.dalelane.Compass getDirection() {
    return direction;
  }


  /**
   * Sets the value of the 'direction' field.
   * @param value the value to set.
   */
  public void setDirection(co.uk.dalelane.Compass value) {
    this.direction = value;
  }

  /**
   * Creates a new Type3 RecordBuilder.
   * @return A new Type3 RecordBuilder
   */
  public static co.uk.dalelane.Type3.Builder newBuilder() {
    return new co.uk.dalelane.Type3.Builder();
  }

  /**
   * Creates a new Type3 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Type3 RecordBuilder
   */
  public static co.uk.dalelane.Type3.Builder newBuilder(co.uk.dalelane.Type3.Builder other) {
    if (other == null) {
      return new co.uk.dalelane.Type3.Builder();
    } else {
      return new co.uk.dalelane.Type3.Builder(other);
    }
  }

  /**
   * Creates a new Type3 RecordBuilder by copying an existing Type3 instance.
   * @param other The existing instance to copy.
   * @return A new Type3 RecordBuilder
   */
  public static co.uk.dalelane.Type3.Builder newBuilder(co.uk.dalelane.Type3 other) {
    if (other == null) {
      return new co.uk.dalelane.Type3.Builder();
    } else {
      return new co.uk.dalelane.Type3.Builder(other);
    }
  }

  /**
   * RecordBuilder for Type3 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Type3>
    implements org.apache.avro.data.RecordBuilder<Type3> {

    private co.uk.dalelane.Compass direction;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(co.uk.dalelane.Type3.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.direction)) {
        this.direction = data().deepCopy(fields()[0].schema(), other.direction);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Type3 instance
     * @param other The existing instance to copy.
     */
    private Builder(co.uk.dalelane.Type3 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.direction)) {
        this.direction = data().deepCopy(fields()[0].schema(), other.direction);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'direction' field.
      * @return The value.
      */
    public co.uk.dalelane.Compass getDirection() {
      return direction;
    }


    /**
      * Sets the value of the 'direction' field.
      * @param value The value of 'direction'.
      * @return This builder.
      */
    public co.uk.dalelane.Type3.Builder setDirection(co.uk.dalelane.Compass value) {
      validate(fields()[0], value);
      this.direction = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'direction' field has been set.
      * @return True if the 'direction' field has been set, false otherwise.
      */
    public boolean hasDirection() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'direction' field.
      * @return This builder.
      */
    public co.uk.dalelane.Type3.Builder clearDirection() {
      direction = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Type3 build() {
      try {
        Type3 record = new Type3();
        record.direction = fieldSetFlags()[0] ? this.direction : (co.uk.dalelane.Compass) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Type3>
    WRITER$ = (org.apache.avro.io.DatumWriter<Type3>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Type3>
    READER$ = (org.apache.avro.io.DatumReader<Type3>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.direction.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.direction = co.uk.dalelane.Compass.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.direction = co.uk.dalelane.Compass.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










