/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gap;
@org.apache.avro.specific.AvroGenerated
public enum Market implements org.apache.avro.generic.GenericEnumSymbol<Market> {
  US, CA, EU, JP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Market\",\"namespace\":\"com.gap\",\"symbols\":[\"US\",\"CA\",\"EU\",\"JP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
